vessel_types = {
    20: 'Wing in ground',
    21: 'Wing in ground, Hazardous category A',
    22: 'Wing in ground, Hazardous category B',
    23: 'Wing in ground, Hazardous category C',
    24: 'Wing in ground, Hazardous category D',
    25: 'Wing in ground',
    26: 'Wing in ground',
    27: 'Wing in ground',
    28: 'Wing in ground',
    29: 'Wing in ground',
    30: 'Fishing',
    31: 'Towing',
    32: 'Towing: length exceeds 200m or breadth exceeds 25m',
    33: 'Dredging or underwater ops',
    34: 'Diving ops',
    35: 'Military ops',
    36: 'Sailing',
    37: 'Pleasure Craft',
    38: 'Reserved',
    39: 'Reserved',
    40: 'High speed craft',
    41: 'High speed craft, Hazardous category A',
    42: 'High speed craft, Hazardous category B',
    43: 'High speed craft, Hazardous category C',
    44: 'High speed craft, Hazardous category D',
    45: 'High speed craft',
    46: 'High speed craft',
    47: 'High speed craft',
    48: 'High speed craft',
    49: 'High speed craft',
    50: 'Pilot Vessel',
    51: 'Search and Rescue vessel',
    52: 'Tug',
    53: 'Port Tender',
    54: 'Anti-pollution equipment',
    55: 'Law Enforcement',
    56: 'Spare - Local Vessel',
    57: 'Spare - Local Vessel',
    58: 'Medical Transport',
    59: 'Noncombatant ship according to RR Resolution No. 18',
    60: 'Passenger',
    61: 'Passenger, Hazardous category A',
    62: 'Passenger, Hazardous category B',
    63: 'Passenger, Hazardous category C',
    64: 'Passenger, Hazardous category D',
    65: 'Passenger',
    66: 'Passenger',
    67: 'Passenger',
    68: 'Passenger',
    69: 'Passenger',
    70: 'Cargo',
    71: 'Cargo, Hazardous category A',
    72: 'Cargo, Hazardous category B',
    73: 'Cargo, Hazardous category C',
    74: 'Cargo, Hazardous category D',
    75: 'Cargo',
    76: 'Cargo',
    77: 'Cargo',
    78: 'Cargo',
    79: 'Cargo',
    80: 'Tanker',
    81: 'Tanker, Hazardous category A',
    82: 'Tanker, Hazardous category B',
    83: 'Tanker, Hazardous category C',
    84: 'Tanker, Hazardous category D',
    85: 'Tanker',
    86: 'Tanker',
    87: 'Tanker',
    88: 'Tanker',
    89: 'Tanker',
    90: 'Other',
    91: 'Other, Hazardous category A',
    92: 'Other, Hazardous category B',
    93: 'Other, Hazardous category C',
    94: 'Other, Hazardous category D',
    95: 'Other',
    96: 'Other',
    97: 'Other',
    98: 'Other',
    99: 'Other'
}